# Generated by Django 4.0.1 on 2022-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_post_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(choices=[('Pushkin', 'Pushkin'), ('Lermantov', 'Lermantov'), ('Esenin', 'Esenin'), ('Gogol', 'Gogol')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_books',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.TextField(null=True),
        ),
    ]
