# Generated by Django 4.0.1 on 2022-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_created_date_remove_book_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.TextField(null=True, verbose_name=int),
        ),
    ]
