# Generated by Django 4.0.1 on 2022-01-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_books',
        ),
    ]
