# Generated by Django 4.0.1 on 2022-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_date_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_books',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
