# Generated by Django 4.0.1 on 2022-01-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_tvshow_date_filmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='quantity',
            field=models.TextField(),
        ),
    ]
