# Generated by Django 4.0.1 on 2022-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_tvshow_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
