# Generated by Django 4.0.1 on 2022-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_tvshow_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='date_filmed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
